[build]
  # 빌드 커맨드: 의존성 설치 후 Nuxt 빌드
  command = "npm install --legacy-peer-deps && npm run build"
  # 배포할 폴더
  publish = ".output/public"
  # Netlify Functions 경로
  functions = ".netlify/functions"

[build.environment]
  # Node 버전 고정 (Netlify Linux 환경)
  NODE_VERSION = "20"
  # npm 설치 시 legacy peer deps 옵션 적용
  NPM_FLAGS = "--legacy-peer-deps"